### ISSUE TITLE
Not loading the stylesheets from jasmine.yml

### ISSUE THREAD

**Issue by HoneyryderChuck** [jasmine/jasmine-gem#201]
Hi, I'm upgrading our jasmine from 1.3.2 to 2.0.0. After dealing with jasmine-jquerya and jasmine-ajax (now mock-ajax), I found out my stylesheets are not being loaded. I have the following jasmine.yml:

``` yaml
src_dir: "app/assets/javascript"
src_files:
   - "application.{js.coffee,js,coffee}"
stylesheets:
  - "./app/assets/stylesheets/application.{css}"
  - " app/assets/stylesheets/application.{css}"
  - "assets/stylesheets/application.{css}"
spec_dir: spec/javascripts
helpers:
  - "helpers/**/*.{js.coffee,js,coffee}"
spec_files:
  - "**/*[Ss]pec.{js.coffee,js,coffee}"
tmp_dir: "tmp/jasmine"
```

but the runner is not loading the application.css. I also tried the three stylesheet path alternatives alone. I am using the asset pipeline, I don't know if it is because of it. I'm also using ruby 1.9.3 with rails 3.2.13. How is this setup?
