### ISSUE TITLE
Jasmine page is not scrollable

### ISSUE THREAD

**Issue by ThomasSzabo** [jasmine/jasmine-gem#277]
The generated "Jasmine suite" HTML page on (default) localhost:8888 is not scrollable. Tested on latest Chrome and Safari.

**Comment by ThomasSzabo** [comment]
This CSS tweak fixes the scrolling issue:

```css
.body {
    overflow-y: scroll;
    position: absolute;
    top: 0px;
    left: 0px;
    bottom: 0px;
    right: 0px;
}
```
