### ISSUE TITLE
CSS for hiding #jasmine_content not properly scoped

### ISSUE THREAD

**Issue by andrewhubbs** [jasmine/jasmine-gem#83]
I am not sure if this belongs here or in the Jasmine core project.

The problem is that the run.html.erb file has the `#jasmine_content div` placed outside the `#HTMLReporter div`. This prevents the styling that pushes the `#jasmine_content div` offscreen because the CSS rule looks like this:

``` css
#HTMLReporter #jasmine_content {
  position: fixed;
  right: 100%;
}
```

The CSS rule either needs to not be scoped around `#HTMLReporter` or the `jasmine.HtmlReporter createReporterDom` function needs to also create the `#jasmine_content div`.

I would be happy to fix the issue but I am not sure where to write a patch.
